name: Terraform Validation

on: [pull_request, push]

jobs:

  validate:
    runs-on: ubuntu-latest
    name: Validating Terraform Templates
    steps:
      - name: Checkouts
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validation
        run: terraform validate